repos:
  - repo: local
    hooks:
      - id: clear-ipynb-output
        name: Clear Jupyter Notebook outputs
        description: Clear Jupyter Notebook outputs
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
        language: system
        files: \.ipynb$
